### ISSUE TITLE
Fixed width table-cell

### ISSUE THREAD

**Issue by gnhuy91** [gnhuy91/til#58]
http://stackoverflow.com/a/4457905/4328963

HTML:

```html
<table>
   <tr>
      <th>header 1</th>
      <th>header 234567895678657</th>
   </tr>
   <tr>
      <td>data asdfasdfasdfasdfasdf</td>
      <td>data 2</td>
   </tr>
</table>
```

CSS:

```css
table{
    border: 1px solid black;
    table-layout: fixed;
    width: 200px;
}

th, td {
    border: 1px solid black;
    width: 100px;
}
```
