### ISSUE TITLE
Dim image on `background-image` property

### ISSUE THREAD

**Issue by gnhuy91** [gnhuy91/til#64]
https://stackoverflow.com/questions/26621513/darken-css-background-image

```css
#landing-wrapper {
    width:100%;
    height:100%;
    background: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url('landingpagepic.jpg');
    background-position:center top;
}
```
