### ISSUE TITLE
Text underline while typing with just CSS

### ISSUE THREAD

**Issue by gnhuy91** [gnhuy91/til#71]
https://codepen.io/FezVrasta/pen/aVpYYV

TL;DR

```html
<div class="input">
  <div class="inner" contenteditable=true placeholder="Search..."></div>
</div>
```

```css
body {
  background-color: #222222;
  color: white;
}

.input {
  font-size: 2em;
  max-width: calc(100vw - 12px)
}
.input::after {
  content: '';
  position: relative;
  display: block;
  border-bottom: 3px solid #333333;
  top: -3px;
  isolation: isolate;
}

.inner {
  position: relative;
  display: inline-block;
  padding: .5em 0;
  border-bottom: 3px solid white;
  z-index: 1;
  font-family: Roboto Slab, sans-serif;
}
.inner:focus {
  border-color: #fbc91b;
}
.inner:empty {
  border-color: transparent;
  width: 100%;
}
.inner:empty::before {
  content: attr(placeholder);
  cursor: text;
  color: #757575;
}

.inner:focus {
  outline: 0;
}
```
