### ISSUE TITLE
Placeholder in contentEditable

### ISSUE THREAD

**Issue by huygn** [gnhuy91/til#79]
```css
[contentEditable=true]:empty:not(:focus):before{
  content:attr(data-placeholder);
  color:grey;
  font-style:italic;
}
```
